import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QMessageBox
class MyApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.setWindowTitle('My PyQt5 App')
        self.setGeometry(100, 100, 300, 200)

        self.button = QPushButton('Click Me', self)
        self.button.setGeometry(100, 80, 100, 30)
        self.button.clicked.connect(self.showMessage)

    def showMessage(self):
        QMessageBox.information(self, 'Message', 'Button Clicked!')
if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyApp()
    ex.show()
    sys.exit(app.exec_())

